#info
title: Roman Yu
title-cn: YY
desc: Departure is just an Attitude!
sub-desc: [Announcement] I get my postgraduate admission of SJTU. And I will study in Shanghai in the next three years(From this Sep.).
disclaimer: Content on this site is my own and in no way represents my employer at anytime. Some of the work, however, is work done for my employer(s).

name: Roman Yu
email: roman_yu@csu.edu.cn
dribbble: http://dribbble.com/awolfe76
github: https://github.com/romanyu
weibo: https://weibo.com/1668843440

#build config
markdown: redcarpet 
